name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RuleMaker
    steps:
    - uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: RuleMaker/build/wwwroot # The folder the action should deploy.
          CLEAN: true
